### ISSUE TITLE
One uncompilable source file in the working directory kills startup

### ISSUE THREAD

**Issue by maifeeulasad** [fluid-ecosystem/fluid-builder#59]
Regression from #26.

Discovery now calls `Class.forName` on every `.java` file in the working directory. Under the source launcher that triggers on-demand compilation, and a compilation failure aborts the whole program — it is **not** catchable, so the `catch (Throwable)` around the load never runs.

Reproduced with an unrelated file that references an absent library:

```
[main] INFO Fluid - 🌊 Fluid Framework Starting 🌀
NeedsMissingJar.java:1: error: package com.example.totally does not exist
2 errors
error: compilation failed
```

The framework starts, then dies. Removing the file, the same service registers its listener normally.

Before #26 only `*Service.java` was loaded, so an unrelated broken file was never touched. Selecting by annotation was the right change — this is the cost of doing it naively.

## Why it matters beyond a stray file

It blocks #58. An optional metrics backend has to ship as a source file that compiles only when its library is present. As things stand that file would abort startup for every service that has **not** enabled metrics, which is the opposite of optional.

## Fix

Pre-filter on source text before loading anything. Read the file, and only attempt `Class.forName` when it mentions a listener annotation. Files that cannot contain a listener are then never compiled, and an unrelated broken file is inert again.

A file that both mentions `@KafkaListener` and fails to compile still aborts — correctly, because that is a real error in something the framework was asked to run.
